USE G3;
Go

CREATE TABLE tbPro(
	productID INTEGER IDENTITY(0001, 1) NOT NULL,
	productName VARCHAR(20) NOT NULL,
	CONSTRAINT prk_pro PRIMARY KEY(productID)
)

Go
CREATE TABLE tbInv(
	invoiceId INTEGER IDENTITY(0001, 1) NOT NULL,
	subTotal INTEGER NOT NULL,
	total INTEGER NOT NULL,
	date DATE NOT NULL,
	CONSTRAINT prk_inv PRIMARY KEY(invoiceId)
)

Go
CREATE TABLE tbInvDetail(
	invoiceNo INTEGER NOT NULL,
	pid INTEGER NOT NULL,
	qty INTEGER NOT NULL,
	CONSTRAINT prk_invDetail PRIMARY KEY(invoiceNo, pid),
	CONSTRAINT fk_pro FOREIGN KEY(pid) REFERENCES tbPro(productID) ON UPDATE CASCADE,
	CONSTRAINT fk_inv FOREIGN KEY(invoiceNo) REFERENCES tbInv(invoiceId) ON UPDATE CASCADE,

)
